### ISSUE TITLE
very slow ui (also seem broken) for 12k samples

### ISSUE THREAD

**Issue by mrVanDalo** [ayyi/samplecat#12]
I use the default config and imported my Samples folder using

> samplecat -g -a ~/Samples

Seems to work, but 
* not every sample has a preview image of the wave.
* searching for e.g. Kick will take like 1 minute for the ui to recover, it always shows something like 'updating 123 Samples' in the bottom left corner. I can also see heavy IO usage. Which I would not expect on a SQL database with a LIKE command and just 12k entries.

I also get this error message on the boot 

```
$ samplecat 
Samplecat. Version 0.2.4
database is sqlite.
warning: default icon theme appears not to contain audio mime-type icons
gl shaders not supported. expect reduced functionality.
auditioner: JACK playback.
Cannot lock down 82274202 byte memory area (Cannot allocate memory)
```

**Comment by mrVanDalo** [comment]
Oh, yeah btw, searching for e.g.: `Kick` will result in a rapid result, but then the ui is frozen for about a minute.

**Comment by ayyi** [comment]
Hi, thanks for your comments.

It is normal for there to be a lot of background IO activity after adding a lot of files. Thumbnails are created and the files are analysed to generate statistics.

However the UI should not be unresponsive. The only issue I am aware of here is when selecting large files in the user interface for the first time. Could that be the case here? Are some of your files quite large?

If the background activity does not eventually clear then it is possible that one or more of the files is unreadable for some reason and you might be seeing an issue where the same unreadable files are attempted to be analyzed each time you start the application. This might explain the memory allocationn error you are seeing. Running samplecat with -v1 or -v2 may help to identify which file is causing the problem.

Also, although it should do no harm, I am curious why your system does not support OpenGl 2. Is your graphics hardware perhaps Intel 945?

Best regards

**Comment by mrVanDalo** [comment]
Hey thanks for the response, 

About the UI, the interface is not responding for quite a while, but after that minute of silence the search results are useable, until the next search. (also if you type in the same search keywords again). I'll try the -v1 -v2 to give you more information.

Hmm I never needed GL so I did configure it. Is it necessary? I don't know why I should need it. But I would configure it, if needed, because I need a sample-sorting program like samplecat.

I'll post more information after I checked the debug informations.

Regards

**Comment by mrVanDalo** [comment]
Ok, I've run it again with samplecat -v2. I can send you the full log if you want.

Here is what I think happend:

* I imported my samples using `samplecat -g -a .`  not naming the folder-name, also I was playing around with the dir-name in the configuration file. 
* I also think, because I Quit some of the "UI freezes" the update algorithm stopped unexpected, and somehow was not able to save the updated state (or something)
* this resulted in always updating the images when typing in a searchphrase.

I'll keep an eye on the strange behavior. I could verify the problem you explained => first time on displaying a sample it will create the image and this takes time, but afterwards everything works smooth, also searching a keyword over and over again will not result in a freeze anymore.

Thank you

p.s.: Maybe you should create the image on `samplecat -g -a Samples`

**Comment by mrVanDalo** [comment]
Keep up the good work and support!

**Comment by ayyi** [comment]
Glad you seem to have it working. I won't do anything for now, but let us know if you have any further problems.
Cheers
