### ISSUE TITLE
Unable to compile on Arch

### ISSUE THREAD

**Issue by bunyi** [ayyi/samplecat#22]
```
ad_ffmpeg.o: In function `ad_read_ffmpeg':
/home/arch/tmp/src/samplecat-0.2.4/src/audio_decoder/ad_ffmpeg.c:249: undefined reference to `avcodec_decode_audio3'
../lib/waveform/waveform/.libs/libwaveform.a(audio_file.o): In function `wf_ff_read':
/home/arch/tmp/src/samplecat-0.2.4/lib/waveform/waveform/audio_file.c:194: undefined reference to `avcodec_decode_audio3'
collect2: error: ld returned 1 exit status
```

Stable version 0.2.4, ffmpeg 3.0.2 gcc 6.1.1

**Comment by ayyi** [comment]
On Tue, Jul 05, 2016 at 05:57:02AM -0700, bunyi wrote:
> ```
> ad_ffmpeg.o: In function `ad_read_ffmpeg':
> /home/arch/tmp/src/samplecat-0.2.4/src/audio_decoder/ad_ffmpeg.c:249: undefined reference to `avcodec_decode_audio3'
> ../lib/waveform/waveform/.libs/libwaveform.a(audio_file.o): In function `wf_ff_read':
> /home/arch/tmp/src/samplecat-0.2.4/lib/waveform/waveform/audio_file.c:194: undefined reference to `avcodec_decode_audio3'
> collect2: error: ld returned 1 exit status
> ```
> Stable version 0.2.4, ffmpeg 3.0.2 gcc 6.1.1
> 
> ---
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/ayyi/samplecat/issues/22

avcodec_decode_audio3 has been deprecated for a while and it
looks like it was removed in ffmpeg-3.0

Samplecat needs to be changed to use avcodec_decode_audio4
instead. It is not a drop in replacement though I have made
the change elsewhere in the code without any apparent ill-effect.
Unfortunately I will not have the time to do this in the next
10 days, but will get to it as soon as possible.

In the meantime, Samplecat is sadly incompatible with
ffmpeg >= 3.0

Thanks for the report

**Comment by ayyi** [comment]
The use of deprecated ffmpeg api has now been removed so hopefully this should allow samplecat to work with ffmpeg-3-0. I will keep the ticket open until I have confirmed this.

**Comment by ayyi** [comment]
I have tested compilation on quite a few platforms now (though not on Arch) and I am not aware of any problems at the moment. I think it is safe to close the ticket. Please re-open if you are still seeing compilation problems.
Thanks again for the report

**Comment by yellius** [comment]
Hi ayyi, I ran into this same issue (also on Arch) using the stable tarball, but latest worked. Perhaps you could up the stable?

**Comment by yellius** [comment]
Hi ayyi, I have another issue I'm afraid. When I run I get this error (first start):
error! g_key_file_set_value: assertion 'value != NULL' failed
warning: cannot connect to database: MYSQL server not online.
sqlite__connect(): SQL: -
database is sqlite.
Segmentation fault (core dumped)

And later (second start):
Samplecat. Version 0.2.5
database is sqlite.
Segmentation fault (core dumped)

Do you have any ideas?

Thanks!
  Jelle.
