### ISSUE TITLE
samplecat gui dosen't open

### ISSUE THREAD

**Issue by AudioMG** [ayyi/samplecat#29]
Hi

I try to setup samplecat on my KXStudio "Ubuntu 14.04".

manfred@kxstudio:/$ samplecat -v 5     
Samplecat. Version 0.2.5
using debug level: 5
get_mime_type(): not found in cache: text/plain
get_mime_type(): not found in cache: inode/directory
get_mime_type(): not found in cache: inode/mount-point
get_mime_type(): not found in cache: inode/fifo
get_mime_type(): not found in cache: inode/socket
get_mime_type(): not found in cache: inode/blockdevice
get_mime_type(): not found in cache: inode/chardevice
get_mime_type(): not found in cache: application/x-executable
get_mime_type(): not found in cache: application/octet-stream
get_mime_type(): not found in cache: application/x-shellscript
get_mime_type(): not found in cache: application/x-desktop
get_mime_type(): not found in cache: inode/unknown
get_mime_type(): not found in cache: inode/door
config loaded.
config_load(): group=Samplecat.
config_load(): database_backend=sqlite
config_load(): window_height=878
config_load(): window_width=1600
config_load(): icon_theme=
config_load(): col1_width=130
config_load(): browse_dir=/home/manfred/mgn_audio/mgn_wav
config_load(): auditioner=
config_load(): jack_autoconnect=system:playback_
config_load(): jack_midiconnect=DISABLED
config_load(): colorkey01=910707
config_load(): colorkey02=bf652f
config_load(): colorkey03=f6cc4d
config_load(): colorkey04=e3ebae
config_load(): colorkey05=4c9107
config_load(): colorkey06=41bf2f
config_load(): colorkey07=4df677
config_load(): colorkey08=aeebd4
config_load(): colorkey09=079191
config_load(): colorkey10=2f89bf
config_load(): colorkey11=4d77f6
config_load(): colorkey12=b5aeeb
config_load(): colorkey13=4c0791
config_load(): colorkey14=ad2fbf
config_load(): colorkey15=f64dcc
config_load(): colorkey16=ebaec5
application_search()...
icon_theme_set_theme(): setting theme: .
icon_theme_init(): icon_theme_path=/home/manfred/.icons
icon_theme_init(): icon_theme_path=/home/manfred/.local/share/icons
icon_theme_init(): icon_theme_path=/usr/share/xubuntu/icons
icon_theme_init(): icon_theme_path=/usr/share/xfce4/icons
icon_theme_init(): icon_theme_path=/usr/local/share/icons
icon_theme_init(): icon_theme_path=/usr/share/icons
icon_theme_init(): icon_theme_path=/usr/share/icons
icon_theme_init(): icon_theme_path=/usr/share/xubuntu/pixmaps
icon_theme_init(): icon_theme_path=/usr/share/xfce4/pixmaps
icon_theme_init(): icon_theme_path=/usr/local/share/pixmaps
icon_theme_init(): icon_theme_path=/usr/share/pixmaps
icon_theme_init(): icon_theme_path=/usr/share/pixmaps
icon_theme_init(): name=oxy-grey
icon_theme_init(): name=oxy-grey
icon_theme_init(): name=oxy-chrome
icon_theme_init(): name=oxy-chrome
icon_theme_init(): name=elementary-xfce
icon_theme_init(): name=elementary-xfce
icon_theme_init(): name=Oxygen Mono Light
icon_theme_init(): name=Oxygen Mono Light
icon_theme_init(): name=oxy-peach
icon_theme_init(): name=oxy-peach
icon_theme_init(): name=elementary-xfce-darkest
icon_theme_init(): name=elementary-xfce-darkest
icon_theme_init(): name=oxy-green
icon_theme_init(): name=oxy-green
icon_theme_init(): name=Oxygen Mono Dark
icon_theme_init(): name=Oxygen Mono Dark
icon_theme_init(): name=DMZ-White
icon_theme_init(): name=DMZ-White
icon_theme_init(): name=oxy-terra
icon_theme_init(): name=oxy-terra
icon_theme_init(): name=oxy-black
icon_theme_init(): name=oxy-black
icon_theme_init(): name=oxy-wonton
icon_theme_init(): name=oxy-wonton
icon_theme_init(): name=oxy-sea_blue
icon_theme_init(): name=oxy-sea_blue
icon_theme_init(): name=oxy-navy
icon_theme_init(): name=oxy-navy
icon_theme_init(): name=elementary-xfce-darker
icon_theme_init(): name=elementary-xfce-darker
icon_theme_init(): name=oxy-desert
icon_theme_init(): name=oxy-desert
icon_theme_init(): name=default.kde4
icon_theme_init(): name=default.kde4
icon_theme_init(): name=hicolor
icon_theme_init(): name=hicolor
icon_theme_init(): name=oxy-olympus
icon_theme_init(): name=oxy-olympus
icon_theme_init(): name=oxy-bluecurve
icon_theme_init(): name=oxy-bluecurve
icon_theme_init(): name=oxy-honeycomb
icon_theme_init(): name=oxy-honeycomb
icon_theme_init(): name=oxy-orchid
icon_theme_init(): name=oxy-orchid
icon_theme_init(): name=default
icon_theme_init(): name=default
icon_theme_init(): name=oxy-whitewater
icon_theme_init(): name=oxy-whitewater
icon_theme_init(): name=oxy-violet
icon_theme_init(): name=oxy-violet
icon_theme_init(): name=oxy-steel
icon_theme_init(): name=oxy-steel
icon_theme_init(): name=oxy-white
icon_theme_init(): name=oxy-white
icon_theme_init(): name=Humanity-Dark
icon_theme_init(): name=Humanity-Dark
icon_theme_init(): name=gnome
icon_theme_init(): name=gnome
icon_theme_init(): name=oxy-hot_orange
icon_theme_init(): name=oxy-hot_orange
icon_theme_init(): name=DMZ-Black
icon_theme_init(): name=DMZ-Black
icon_theme_init(): name=oxy-obsidian-hc
icon_theme_init(): name=oxy-obsidian-hc
icon_theme_init(): name=oxy-terra_green
icon_theme_init(): name=oxy-terra_green
icon_theme_init(): name=oxy-olympus-inv
icon_theme_init(): name=oxy-olympus-inv
icon_theme_init(): name=oxy-viorange
icon_theme_init(): name=oxy-viorange
icon_theme_init(): name=HighContrast
icon_theme_init(): name=HighContrast
icon_theme_init(): name=oxy-zion
icon_theme_init(): name=oxy-zion
icon_theme_init(): name=oxy-emerald
icon_theme_init(): name=oxy-emerald
icon_theme_init(): name=oxy-purple
icon_theme_init(): name=oxy-purple
icon_theme_init(): name=oxy-cherry
icon_theme_init(): name=oxy-cherry
icon_theme_init(): name=oxy-red-argentina
icon_theme_init(): name=oxy-red-argentina
icon_theme_init(): name=KDE_Classic
icon_theme_init(): name=KDE_Classic
icon_theme_init(): name=oxy-yellow
icon_theme_init(): name=oxy-yellow
icon_theme_init(): name=elementary-xfce-dark
icon_theme_init(): name=elementary-xfce-dark
icon_theme_init(): name=oxy-red
icon_theme_init(): name=oxy-red
icon_theme_init(): name=oxy-brown
icon_theme_init(): name=oxy-brown
icon_theme_init(): name=oxy-lilac
icon_theme_init(): name=oxy-lilac
icon_theme_init(): name=oxy-blue
icon_theme_init(): name=oxy-blue
icon_theme_init(): name=oxygen
icon_theme_init(): name=oxygen
icon_theme_init(): name=Humanity
icon_theme_init(): name=Humanity
icon_theme_init(): name=oxy-midnight_meadow
icon_theme_init(): name=oxy-midnight_meadow
icon_theme_init(): name=oxy-obsidian
icon_theme_init(): name=oxy-obsidian
icon_theme_init(): name=oxy-norway
icon_theme_init(): name=oxy-norway
icon_theme_init(): name=oxy-oxygen
icon_theme_init(): name=oxy-oxygen
sqlite__connect()...
sqlite__connect(): found table 'samples'
database is sqlite.
worker_thread_init(): creating overview thread...
worker_thread(): new worker thread.
gdl_dock_item_new(): Library
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_new(): Search
gdl_dock_object_dock()...
gdl_dock_item_dock()...
warning: gdl_dock_item_dock(): using allocation of unrealized widget
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=__dock_1 (GdlDock)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
gdl_dock_item_new(): Filters
gdl_dock_object_dock()...
gdl_dock_item_dock()...
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=<unnamed> (GdlDockPaned)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
gdl_dock_item_new(): Inspector
gdl_dock_object_dock()...
gdl_dock_item_dock()...
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=<unnamed> (GdlDockPaned)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
gdl_dock_item_new(): Directories
gdl_dock_object_dock()...
gdl_dock_item_dock()...
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=<unnamed> (GdlDockPaned)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
gdl_dock_item_new(): Filemanager
gdl_dock_object_dock()...
gdl_dock_item_dock()...
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=<unnamed> (GdlDockPaned)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
gdl_dock_item_new(): Player
gdl_dock_object_dock()...
gdl_dock_item_dock()...
gdl_dock_item_dock(): req.width _not_ set. using width from object_req: 1
gdl_dock_item_dock(): available_space set from parent_req.width: 1
gdl_dock_item_dock(): GDL_DOCK_LEFT/RIGHT: pref_size set from req.width
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
gdl_dock_item_dock(): new_parent: pref_size=0
gdl_dock_object_dock()...
gdl_dock_object_dock(): done
warning: gdl_dock_item_dock(): GDL_DOCK_LEFT. not setting split point! object too big? splitpos=0 available_space=1
warning: gdl_dock_item_dock(): ... parent=<unnamed> (GdlDockPaned)
warning: gdl_dock_item_dock(): ... new_parent=<unnamed> (GdlDockPaned)
gdl_dock_object_dock(): done
make_accels(): user_data=(nil) Quit.
make_accels(): path=<Samplecat-window>/Categ/Quit
shortcuts_add_action(): group=Samplecat-window group_size=1 action=Quit
make_accels(): user_data=(nil) Close.
make_accels(): path=<Samplecat-window>/Categ/Close
shortcuts_add_action(): group=Samplecat-window group_size=2 action=Close
make_accels(): user_data=(nil) Delete.
make_accels(): path=<Samplecat-window>/Categ/Delete
shortcuts_add_action(): group=Samplecat-window group_size=3 action=Delete
make_accels(): user_data=(nil) Layout Manager.
make_accels(): path=<Samplecat-window>/Categ/Layout Manager
shortcuts_add_action(): group=Samplecat-window group_size=4 action=Layout Manager
window_on_allocate(): fg_color: 3c3c 3c3c 3c3c
window_on_allocate(): dedede 3c3c3c
application_search()...
samplecat_list_store_clear_()...
sqlite__search_iter_new()...
sqlite__search_iter_new():  AND (  (filename LIKE '%/home/manfred/mgn%' OR filedir LIKE '%/home/manfred/mgn%' OR keywords LIKE '%/home/manfred/mgn%')  AND (filename LIKE '%audio/%' OR filedir LIKE '%audio/%' OR keywords LIKE '%audio/%') )
sqlite__search_iter_new(): sql=SELECT * FROM samples WHERE 1  AND (  (filename LIKE '%/home/manfred/mgn%' OR filedir LIKE '%/home/manfred/mgn%' OR keywords LIKE '%/home/manfred/mgn%')  AND (filename LIKE '%audio/%' OR filedir LIKE '%audio/%' OR keywords LIKE '%audio/%') )
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
get_mime_type(): not found in cache: audio/x-wav
mimetype_is_unsupported(): mimetype ok: audio/x-wav
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
mimetype_is_unsupported(): mimetype ok: audio/x-wav
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
mimetype_is_unsupported(): mimetype ok: audio/x-wav
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
mimetype_is_unsupported(): mimetype ok: audio/x-wav
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
mimetype_is_unsupported(): mimetype ok: audio/x-wav
blob_to_pixbuf(): decompressed pixbuf 90 -> 16024
mimetype_is_unsupported(): mimetype ok: audio/x-wav
showing 6 of 6 sample(s)
application_set_ready(): loaded
Samplecat. Version 0.2.5
window_on_configure(): setting size: width=1600 height=878
window_load_layout()...
window_load_layout(): loading layout: __default__
gdl_dock_layout_setup_object(): object_name=__dock_1 object=0x1739700
window_activate_layout()...
gdl_dock_layout_setup_object(): object_name=__dock_1 object=0x1739700
gdl_dock_print_recursive(): ...
   0 __dock_1
_on_layout_changed()...
Speicherzugriffsfehler (Speicherabzug geschrieben)
manfred@kxstudio:/$ 

Bevore it was possible to open the GUI and I had insert some files.

manfred@kxstudio:/$ samplecat --no-gui
Samplecat. Version 0.2.5
database is sqlite.
  KHOboe_stac_Ab4_ff2.wav        mgn_audio/mgn_wav/50_Orchestral_Sa      615 2 44100 audio/x-wav
  LDFlute_trillW_C4_v1_1.wav     mgn_audio/mgn_wav/50_Orchestral_Sa     6085 2 44100 audio/x-wav
  LDFlute_expvib_D4_v1_1.wav     mgn_audio/mgn_wav/50_Orchestral_Sa    10261 2 44100 audio/x-wav
  KSHarp_A4_mf1.wav              mgn_audio/mgn_wav/50_Orchestral_Sa    12151 2 44100 audio/x-wav
  KSHarp_A2_f1.wav               mgn_audio/mgn_wav/50_Orchestral_Sa    11093 2 44100 audio/x-wav
  Tuba2_sus_A#0_v3_1.wav         mgn_audio/mgn_wav/50_Orchestral_Sa     6397 2 44100 audio/x-wav
total 6 samples found.
manfred@kxstudio:/$ 

But now it is not anymore possible to start the GUI.

What can I do now?

Best regards
Manfred

**Comment by ayyi** [comment]
Hi
Sorry to hear you are having problems
You didn't say what happened between it working and then not working. I will assume you did a git pull.

If you do 'git log' you will see  a list of commits. You can go back to a previous commit by doing for example 'git checkout 60d6bf893b8016d2da214e560b1eb918d3a1780a', then recompiling. You might have to do the same thing in the lib/waveform directorỵ.

Another thing you could try is to work out which window panel is causing the problem. You can do this by editing the ``~/.config/samplecat/layouts/__default__.xml`` file.
Each layout in this file should look something like this:
``` xml
<layout name="__default__">
    <dock name="__dock_1" floating="no" width="-1" height="-1" floatx="0" floaty="0">
        <paned orientation="vertical" locked="no" position="78">
            <item name="Search" orientation="vertical" locked="yes"/>
            <paned orientation="vertical" locked="no" position="232">
                <paned orientation="horizontal" locked="no" position="124">
                    <paned orientation="vertical" locked="no" position="160">
                        <item name="Directories" orientation="vertical" locked="no"/>
                        <item name="Inspector" orientation="vertical" locked="no"/>
                    </paned>
                    <notebook orientation="vertical" locked="no" page="0">
                        <item name="Library" orientation="vertical" locked="yes"/>
                        <item name="Filemanager" orientation="vertical" locked="no"/>
                    </notebook>
                </paned>
                <item name="Waveform" orientation="vertical" locked="no"/>
            </paned>
        </paned>
    </dock>
</layout>
```
You appear to be using the ``__default__`` layout. You could try removing each 'item' in turn to try and determine which window panel is causing the problem.

Hope that helps

**Comment by AudioMG** [comment]
Hello

I had yesterday faced also some other problems for example
with the Synaptic GUI and even with some other GUIs. 
I assume something with my OS is confused. I will re install
the OS and test it again. I will let you know If I am ready.

Best regards
Manfred

**Comment by ayyi** [comment]
Please re-open the ticket if the problem persists
Cheers
