### ISSUE TITLE
Windows and OSX versions?

### ISSUE THREAD

**Issue by naught101** [ayyi/samplecat#4]
Just wondering how difficult it would be to get Windows and OSX versions happening? I don't use either my self, but I'd love to be able to recommend something like this to friends who aren't ready to move to Linux. It's clear from [posts like this](http://www.reddit.com/r/edmproduction/comments/1b6arp/is_there_any_good_software_for_browsing_samples/) that there's a niche available on both systems...

**Comment by ayyi** [comment]
I will close the ticket as there is nothing actionable.

I would appreciate input from anyone on whether the latest tarball has inadvertently broken anything on OSX.
