### ISSUE TITLE
Unresponsive UI after start

### ISSUE THREAD

**Issue by mxmilkiib** [ayyi/samplecat#41]
I get the main window up after starting with UI items. Visually, there is a problem in that there's a basic file with red x icon for the sound files I had loaded last time I was testing, but the main issue is that after that the UI doesn't respond. I can float the window in swaywm, but making the window smaller then larger again 'wipes' the UI graphics away.

I'm using wayland, but I've tried under Xwayland also with the same result.

The console text I get is

```
Samplecat 0.3.0
warning: default icon theme appears not to contain audio mime-type icons
warning: default icon theme appears not to contain audio mime-type icons
warning: Failed to set text from markup due to error parsing markup: Error on line 1 char 17: Odd character “>”, expected a “=” after attribute name “tags” of element “no”
warning: Failed to set text from markup due to error parsing markup: Error on line 1 char 17: Odd character “>”, expected a “=” after attribute name “tags” of element “no”
warning: Failed to set text from markup due to error parsing markup: Error on line 1 char 17: Odd character “>”, expected a “=” after attribute name “tags” of element “no”
auditioner: JACK playback.
^C
```

**Comment by ayyi** [comment]
Hi
From your description, I unfortunately don't have any good ideas as to what might be happening. I have been meaning to try Wayland but as yet have not done so.

**Comment by ayyi** [comment]
Changes have been made recently that may have helped with this issue.

I would like to close. Please do re-open if the problem remains. If that is the case there are some things we can try to find the cause.

Thanks
