### ISSUE TITLE
CI

### ISSUE THREAD

**Issue by mxmilkb** [ayyi/samplecat#43]
https://en.wikipedia.org/wiki/Continuous_integration

If there was an automated build of the software, it would quickly feedback as to whether the master branch is broken or not.

**Comment by ayyi** [comment]
There are build tests in the test directory, but they are not run automaticallỵ
I will look into using Travis.
Or do you have any specific recomendations?

**Comment by mxmilkb** [comment]
Travis is indeed probably a safe bet. https://github.com/marketplace/travis-ci

**Comment by ayyi** [comment]
I have implemented build testing on gitlab and the homepage should show the current build status. Currently the test targets are Debian-10 and Ubuntu-18. We can add some more in the future.
@mxmilkb thanks for the prompt.
