### ISSUE TITLE
Can't configure

### ISSUE THREAD

**Issue by davidhealey** [ayyi/samplecat#44]
Running ./configure.ac I get 

```
./configure: line 1: syntax error near unexpected token `2.59'
./configure: line 1: `AC_PREREQ(2.59)'
```

I assume I'm doing something wrong?

**Comment by ayyi** [comment]
Hi
I think autogen is what you are looking for
```./autogen.sh```
This will generate the configure script which you can then run.
Cheers

**Comment by davidhealey** [comment]
Oh ok, thanks :) I'll try it now

**Comment by davidhealey** [comment]
Yup that was the issue, I didn't read the install instructions correctly!

I'm getting this error though

```
player.h:17:10: fatal error: waveform/promise.h: No such file or directory
 #include "waveform/promise.h"
```
I've downloaded the sub-module and the file isn't in there, I also can't see it in the git repo.

**Comment by ayyi** [comment]
Hi
Can you try (in the samplecat directory):
```
git submodule foreach git pull origin master
```
If that doesnt work perhaps try (in a new directory):
```
wget https://raw.githubusercontent.com/ayyi/samplecat/master/test/debian-10/Makefile
make
```
Cheers

**Comment by davidhealey** [comment]
The second method worked perfectly, thanks!
