### ISSUE TITLE
Crashes when trying to generate waveform for super short files

### ISSUE THREAD

**Issue by chrisbeckstrom** [ayyi/samplecat#45]
Hi! This is truly amazing, thanks for making this software. I have a sample library with 30k samples and this is really going to help me find and organize my sounds.

I'm having trouble with some files, and it seems I need to completely remove them from my library for Samplecat to work.

Steps to reproduce:

- Run samplecat gui (`samplecat -p cli -v2`)
- Search using a term that has lots of results, for instance "acoustic"
- Many results are returned, but soon the program crashes

Here is the last bit of the stdout output:

```
make_overview(): NEW OVERVIEW
waveform_get_peak_filename(): uri=file:///home/chris/Nextcloud/Samples/acoustic_sounds/drums/2019-03-14_kid_drumset_basement/kids_drums_SM57_135BPM-1.1/kids_drums_SM57_135BPM-1.1009.wav
waveform_get_peak_filename(): peak_filename=/home/chris/.cache/peak/da4f1bbdc783a4df24eab72b513ea39e.peak
wf_peakgen__sync()...
pixbuf_to_blob(): compressed pixbuf 12024 -> 640
updating 210 items...
pixbuf_to_blob(): compressed pixbuf 12024 -> 1366
wf_load_riff_peak()...
wf_load_riff_peak(): n_channels=1 n_frames=34464 n_bytes=137856 n_blocks=135
wf_load_riff_peak(): secs=0.781 200.063
waveform_peakbuf_malloc(): peak cache: size=110k
waveform_load_peak(): ch=0 num_peaks=34464
get_buf_info(): MED len=0 0 (x256=0)
waveform_peak_to_pixbuf_full(): done. xmag=172.31 drawn: 200 of 200 src=0-->34462
waveform_finalize()...
waveform_audio_free()...
waveform_finalize(): done
make_overview(): NEW OVERVIEW
waveform_get_peak_filename(): uri=file:///home/chris/Nextcloud/Samples/acoustic_sounds/drums/2019-03-14_kid_drumset_basement/kids_drums_SM57_135BPM-1.1/kids_drums_SM57_135BPM-1.1010.wav
waveform_get_peak_filename(): peak_filename=/home/chris/.cache/peak/8278899fdf5643db45811aaebdf71fc0.peak
wf_peakgen__sync()...
wf_load_riff_peak()...
wf_load_riff_peak(): n_channels=1 n_frames=0 n_bytes=0 n_blocks=0
wf_load_riff_peak(): secs=0.000 0.000
waveform_peakbuf_malloc(): peak cache: size=42k
Segmentation fault (core dumped)
```

I think that particular error is due to samplecat not knowing what to do with a file that seems to be empty, or very very very short, this file: `uri=file:///home/chris/Nextcloud/Samples/acoustic_sounds/drums/2019-03-14_kid_drumset_basement/kids_drums_SM57_135BPM-1.1/kids_drums_SM57_135BPM-1.1010.wav`

I'm not entirely sure how I got such short (empty?) audio files, but I think it's related to how I automatically slice up recorded samples; I think sometimes my slicing creates (infinitely?) short files.

EDIT: this happens in both the 0.3.0 tarball compiled version as well as a version compiled from the current github files.

system details:

```
LSB Version:    core-9.20160110ubuntu0.2-amd64:core-9.20160110ubuntu0.2-noarch:security-9.20160110ubuntu0.2-amd64:security-9.20160110ubuntu0.2-noarch
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.6 LTS
Release:        16.04
Codename:       xenial
```

**Comment by ayyi** [comment]
Thanks, I will add a test for empty files

**Comment by ayyi** [comment]
A [fix](https://github.com/ayyi/libwaveform/commit/174d23ab8374041a75afe9d6483d5019b58e9dea) was made for this on Dec 6th.

I will keep the ticket open until a test has been added.
