### ISSUE TITLE
0.3.0 tag and release archive missing?

### ISSUE THREAD

**Issue by simonvanderveldt** [ayyi/samplecat#47]
The site lists 0.3.0 as the latest version, with a link to http://www.orford.org/assets/samplecat-0.3.0.tar.gz for the sources but there is no tag in git nor a release in this repo for this version. Could these be added?

The same goes for 0.2.4 btw.

**Comment by ayyi** [comment]
Hi, thanks for pointing out the missing tag.

I have created tag v0.3.0 and added a 'release':
https://gitlab.com/ayyi.org/samplecat/-/releases

I will try and do this for future releases. I have not done the same for older releases as I think they are too old to be of any interest to people.

Let me know if there is anything further that should be done.

Regards

**Comment by ayyi** [comment]
Please re-open if there is anything further to be done
Thanks
