### ISSUE TITLE
Unable to build samplecat 0.3.0

### ISSUE THREAD

**Issue by Yann-Kaelig** [ayyi/samplecat#50]
Unable to build samplecat 0.3.0 on Arch.

[PKGBUILD.TXT](https://github.com/ayyi/samplecat/files/4060892/PKGBUILD.TXT)

[samplecat-0.3.0-log.txt](https://github.com/ayyi/samplecat/files/4060895/samplecat-0.3.0-log.txt)

Operating System: Architekt 
KDE Plasma Version: 5.17.5
KDE Frameworks Version: 5.65.0
Qt Version: 5.14.0
Kernel Version: 5.3.12-arch1-3-desktop-ARCHITEKT
OS Type: 64-bit

**Comment by ayyi** [comment]
Hi, thanks for the report.

I believe this is the same issue as https://github.com/ayyi/libwaveform/issues/5

A change was made in the master branch to remove use of deprecated pango functions but I don't know if this fixes your problem or not.

I can do two things:
 1. If you can confirm that git master compiles ok on your system I can make a new release
 2. I can add Arch as a CI target to make sure this doesn't happen again. Arch is so cutting edge its always interesting to see whats coming down the pipeline :-)

**Comment by Yann-Kaelig** [comment]
Hi,

Unfortunately with git master the build failed.

[samplecat-git-log.txt](https://github.com/ayyi/samplecat/files/4066113/samplecat-git-log.txt)

**Comment by ayyi** [comment]
Thanks for the information.
I have [added a build test for Arch](https://github.com/ayyi/samplecat/commit/ec9c35a55acab1c6487c556c10968a1d8d3c9b57)
I will do the actual fix next.
Regards

**Comment by ayyi** [comment]
I believe it should build now but I have had to disable text on the waveform until issues with Pango 1.44 are resolved.
Please see the [libwaveform issue](https://github.com/ayyi/libwaveform/issues/5) for details.

**Comment by grammoboy2** [comment]
Debian testing:

fontmap.c: In function ‘pango_gl_font_map_class_init’:
fontmap.c:222:42: warning: implicit declaration of function ‘PANGO_FC_FONT_MAP_CLASS’; did you mean ‘PANGO_IS_FONT_MAP_CLASS’? [-Wimplicit-function-declaration]
  222 |   PangoFcFontMapClass *fcfontmap_class = PANGO_FC_FONT_MAP_CLASS (class);
      |                                          ^~~~~~~~~~~~~~~~~~~~~~~
      |                                          PANGO_IS_FONT_MAP_CLASS
fontmap.c:222:42: warning: initialization of ‘PangoFcFontMapClass *’ {aka ‘struct _PangoFcFontMapClass *’} from ‘int’ makes pointer from integer without a cast [-Wint-conversion]
fontmap.c:225:18: error: dereferencing pointer to incomplete type ‘PangoFcFontMapClass’ {aka ‘struct _PangoFcFontMapClass’}
  225 |   fcfontmap_class->default_substitute = pango_gl_font_map_default_substitute;
      |                  ^~
make[7]: *** [Makefile:534: fontmap.lo] Error 1
make[7]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib/waveform/agl'
make[6]: *** [Makefile:574: all-recursive] Error 1
make[6]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib/waveform/agl'
make[5]: *** [Makefile:450: all] Error 2
make[5]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib/waveform/agl'
make[4]: *** [Makefile:611: all-recursive] Error 1
make[4]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib/waveform'
make[3]: *** [Makefile:476: all] Error 2
make[3]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib/waveform'
make[2]: *** [Makefile:417: all-recursive] Error 1
make[2]: Leaving directory '/home/debian/develop/samplecat-0.3.0/lib'
make[1]: *** [Makefile:542: all-recursive] Error 1
make[1]: Leaving directory '/home/debian/develop/samplecat-0.3.0'
make: *** [Makefile:431: all] Error 2

**Comment by ayyi** [comment]
Hi @grammoboy2, thanks for the report.

The latest update on this issue is that deprecations in Pango have forced some major changes to the code. The work is in the 'gsk' branch. I believe the branch is stable and intend to merge it to master quite soon.

Please switch to the 'gsk' branch and let me know if you have any problems.

Regards

**Comment by grammoboy2** [comment]
That branch seems to build indeed.

**Comment by ayyi** [comment]
I have merged these changes to Master. Unless there are any comments in the next few days, I will create release 0.3.1

**Comment by sone** [comment]
Hi, after cloning and updateing the submodules there is no lib/agl directory and there is a configure error as visible in the attached output of ./configure.

[samplecat-configure-focal.txt](https://github.com/ayyi/samplecat/files/5889209/samplecat-configure-focal.txt)

**Comment by ayyi** [comment]
Hi @sone

You didn't say exactly how you initialised the project but if initialising the sub-projects manually it is now necessary to use the --recursive option. However it is easier to let the autogen.sh script do this for you.

The recommended way to build is this:

```
git clone https://github.com/ayyi/samplecat.git
cd samplecat
./autogen.sh
./configure
make
```
Thanks

**Comment by sone** [comment]
Hi @ayyi 
I was missing:
sudo apt-get -y install libgraphene-1.0-dev 
Now it builds.
Cheers

**Comment by ayyi** [comment]
With an Arch CI build now in place, hopefully these kind of build errors will not happen in the future.
