### ISSUE TITLE
Constant output of the same error message after start

### ISSUE THREAD

**Issue by mxmilkiib** [ayyi/samplecat#51]
```
!!! unhandled bit depth: 0
```

over and over, very quickly.

**Comment by ayyi** [comment]
Hi
This is related to libsndfile.
Please can you

1. tell us which version of libsndfile is on your system
1. git pull && git submodule foreach git pull origin master && make
2. run samplecat with --verbose 1
3. post a few lines of output (at least 20) - I'm expecting it now to say 'missing format' and which files are causing the error - I take it your files are not in some unusual format?

Thanks

**Comment by ayyi** [comment]
Please feel to re-open the ticket if the problem still exists. Thanks
