### ISSUE TITLE
error when build - make 

### ISSUE THREAD

**Issue by p-k-l** [ayyi/samplecat#52]
hello i have this error when make 

In file included from ../../agl/text/renderer.h:24,
                 from clip.c:19:
../../agl/text/renderops.h:16:10: fatal error: graphene.h: No such file or directory
   16 | #include <graphene.h>
      |          ^~~~~~~~~~~~
compilation terminated.

more info 
killum@killum:~/Downloads/samplecat-0.3.1$ cat /usr/include/pango-1.0/pango/pangofc-fontmap.h | grep 'struct _PangoFcFontMap'
typedef struct _PangoFcFontMap        PangoFcFontMap;
typedef struct _PangoFcFontMapClass   PangoFcFontMapClass;
typedef struct _PangoFcFontMapPrivate PangoFcFontMapPrivate;
killum@killum:~/Downloads/samplecat-0.3.1$ pkg-config pango --modversion
1.46.2
killum@killum:~/Downloads/samplecat-0.3.1$ pkg-config pango --cflags
-pthread -I/usr/include/pango-1.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/freetype2 -I/usr/include/libpng16

**Comment by ayyi** [comment]
Hi @p-k-l 
I think you might need to install libgraphene-1.0-dev
This was a new dependency that was recently added.
I will check the configure script aborts if this dependency is not met ...
If you are on Ubuntu,  a list of dependencies can be seen in the file test/ubuntu-18/dependencies
Thanks

**Comment by p-k-l** [comment]
Hi @ayyi 
thanks for reply
after i install libgraphene-1.0-dev previous error solved
but not build successful 
my all log in [here](https://justpaste.it/80sb9)

**Comment by ayyi** [comment]
Hi @p-k-l 
Glad we are making some progress.
I can see from the log that the application was installed as /usr/local/bin/samplecat .
If you run this, what are you seeing?
Cheers

**Comment by p-k-l** [comment]
> Hi @p-k-l
> Glad we are making some progress.
> I can see from the log that the application was installed as /usr/local/bin/samplecat .
> If you run this, what are you seeing?
> Cheers
