### ISSUE TITLE
Fatal error during make install

### ISSUE THREAD

**Issue by fasteddy13** [ayyi/samplecat#53]
`window.c:62:10: fatal error: ../layouts/layouts.c: No such file or directory
   62 | #include "../layouts/layouts.c"
      |          ^~~~~~~~~~~~~~~~~~~~~~
`
Relevant log:
[make-install-log.txt](https://github.com/ayyi/samplecat/files/5560882/make-install-log.txt)

**Comment by ayyi** [comment]
Hi

layouts/layouts.c is a generated file which for some reason has not been generated.

What system are you on, what source are you building from, and what commands did you run? Did you run `make` before `make install`?

What happens if you cd into the layouts directory and run `make` there?

Thanks

**Comment by fasteddy13** [comment]
My apologies, I forgot to do `make`. However, running `make` leads to this error:

`../../agl/text/renderops.h:16:10: fatal error: graphene.h: No such file or directory`

I have the libgraphene-1.0-dev package installed, what can be done to fix this?

**Comment by ayyi** [comment]
Ok, good, we are making some progress!

What system are you on? (eg Ubuntu 18)

can you tell the the output of these:
`pkg-config --cflags graphene-1.0`
`pkg-config --modversion graphene-1.0`
`ls -l /usr/include/graphene-1.0/`

Thanks

**Comment by fasteddy13** [comment]
The system I am on is Ubuntu Studio 20.0.4.

Here is the output of those commands:
```
steve@Z170X:/media/steve/Apps/samplecat/samplecat-0.3.1$ pkg-config --cflags graphene-1.0
-mfpmath=sse -msse -msse2 -I/usr/include/graphene-1.0 -I/usr/lib/x86_64-linux-gnu/graphene-1.0/include -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include
steve@Z170X:/media/steve/Apps/samplecat/samplecat-0.3.1$ pkg-config --modversion graphene-1.0
1.10.0
steve@Z170X:/media/steve/Apps/samplecat/samplecat-0.3.1$ ls -l /usr/include/graphene-1.0/
total 300
-rw-r--r-- 1 root root  7944 Sep  8  2019 graphene-box.h
-rw-r--r-- 1 root root 11368 Sep  8  2019 graphene-euler.h
-rw-r--r-- 1 root root  4174 Sep  8  2019 graphene-frustum.h
-rw-r--r-- 1 root root  3589 Sep  8  2019 graphene-gobject.h
-rw-r--r-- 1 root root  1992 Sep  8  2019 graphene.h
-rw-r--r-- 1 root root  3689 Sep  8  2019 graphene-macros.h
-rw-r--r-- 1 root root 20894 Sep  8  2019 graphene-matrix.h
-rw-r--r-- 1 root root  5108 Sep  8  2019 graphene-plane.h
-rw-r--r-- 1 root root  6804 Sep  8  2019 graphene-point3d.h
-rw-r--r-- 1 root root  4755 Sep  8  2019 graphene-point.h
-rw-r--r-- 1 root root  3252 Sep  8  2019 graphene-quad.h
-rw-r--r-- 1 root root  9146 Sep  8  2019 graphene-quaternion.h
-rw-r--r-- 1 root root  6943 Sep  8  2019 graphene-ray.h
-rw-r--r-- 1 root root  9979 Sep  8  2019 graphene-rect.h
-rw-r--r-- 1 root root 58289 Sep  8  2019 graphene-simd4f.h
-rw-r--r-- 1 root root 39733 Sep  8  2019 graphene-simd4x4f.h
-rw-r--r-- 1 root root  3870 Sep  8  2019 graphene-size.h
-rw-r--r-- 1 root root  4696 Sep  8  2019 graphene-sphere.h
-rw-r--r-- 1 root root  6292 Sep  8  2019 graphene-triangle.h
-rw-r--r-- 1 root root  4099 Sep  8  2019 graphene-types.h
-rw-r--r-- 1 root root  6865 Sep  8  2019 graphene-vec2.h
-rw-r--r-- 1 root root  8490 Sep  8  2019 graphene-vec3.h
-rw-r--r-- 1 root root  8434 Sep  8  2019 graphene-vec4.h
-rw-r--r-- 1 root root  2106 Dec 10  2019 graphene-version.h
-rw-r--r-- 1 root root  8375 Sep  8  2019 graphene-version-macros.h
```

**Comment by ayyi** [comment]
Thanks for that.

That all looks as expected so I can't see why the compiler can't find graphene.h

I will set up an Ubuntu 20 test here...

[One hour later]

Ok, I tried on Ubuntu 20.04 and it compiled ok when running this command

```
git clone --branch "master" https://github.com/ayyi/samplecat.git
cd samplecat && \
        git submodule update --init && \
        ./autogen.sh && \
        ./configure --enable-test && \
        make && \
        ./src/samplecat --version
```
Could you try the same thing?

Thanks

**Comment by fasteddy13** [comment]
I've attempted to do this, but run into an issue while running the `make` portion:
`make[7]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/waveform/test/gen'
Generating 10s test wav
Sndfile open failed '../data/mono_0:10.wav': System error : Invalid argument.
../data/mono_0:10.wav: No such file or directory
../data/mono_0:10.wav: No such file or directory
../data/mono_0:10.wav: No such file or directory
../data/mono_0:10.wav: No such file or directory
../data/mono_0:10.wav: No such file or directory
../data/mono_0:10.wav: No such file or directory
Sndfile open failed: System error : Invalid argument.
Generating 10s test wav
Sndfile open failed '--channels=2': System error : Invalid argument.
../data/stereo_0:10.wav: No such file or directory
../data/stereo_0:10.wav: No such file or directory
../data/stereo_0:10.wav: No such file or directory
../data/stereo_0:10.wav: No such file or directory
../data/stereo_0:10.wav: No such file or directory
make[6]: *** [Makefile:860: test_data] Error 1
make[6]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/waveform/test/gen'
make[5]: *** [Makefile:1222: all-recursive] Error 1
make[5]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/waveform/test'
make[4]: *** [Makefile:636: all-recursive] Error 1
make[4]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/waveform'
make[3]: *** [Makefile:498: all] Error 2
make[3]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/waveform'
make[2]: *** [Makefile:421: all-recursive] Error 1
make[2]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib'
make[1]: *** [Makefile:555: all-recursive] Error 1
make[1]: Leaving directory '/media/steve/Apps/samplecat/samplecat'
make: *** [Makefile:444: all] Error 2`

**Comment by ayyi** [comment]
For some reason the test data did not get generated.

Sorry, but could you try again but without the "--enable-test"

Thanks

**Comment by fasteddy13** [comment]
Thank you, samplecat built fine.

**Comment by fasteddy13** [comment]
Hi..
Got it installed, opens ok, but crashes when I choose 'Add to database' for any wave file. Also dont seem to have the context menu showing. Is there any info (readme file?) to help with the config file settings? Perhaps I do not have the config file right yet, have not changed it yet.

**Comment by ayyi** [comment]
Hi

That is a good point about the config file, I can add some extra text describing the options.

However, it should be as simple as using values 'mysql' or 'sqlite' for `database_backend`. It will default to sqlite if supported.

Can you paste the output of samplecat when running with `---verbose 1` ? A gdb backtrace would be even better but I am assuming you don't have gdb installed

Also it would be useful to see the output of
```
cat config.log | grep result: | tail -n 40
```

Thanks

**Comment by fasteddy13** [comment]
Using `---verbose 1` (with 3 dashes) results in an immediate segfault:
```
steve@Z170X:/media/steve/Apps/samplecat$ samplecat ---verbose 1
Samplecat 0.3.1
Segmentation fault (core dumped)
```
Using `--verbose 1` leads to this when adding a sample to database:
```
waveform_load_audio_run_job(): block=0 tot_audio_mem=0kB
ops_free()...
waveform_load_audio_run_job(): block=1 tot_audio_mem=0kB
waveform_load_audio_run_job(): block=2 tot_audio_mem=0kB
add_section: HI 0 block_size=32k section->buffer=96k
ng_gl2_load_block: 0: uploading texture: 4096 x 24
_wf_actor_on_peakdata_available: block=0
ng_gl2_load_block: 0: uploading texture: 4096 x 24
_wf_actor_on_peakdata_available: block=1
ops_free()...
__clean: size=1
ng_gl2_load_block: 0: uploading texture: 4096 x 24
section_is_complete: complete
_wf_actor_on_peakdata_available: block=2
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
ops_free()...
on_transition_finished()...
ops_free()...
menu__add_to_db()...
referencing files..
Segmentation fault (core dumped)
```
Here is the output of the command you specified:
[grep-log.txt](https://github.com/ayyi/samplecat/files/5580104/grep-log.txt)

**Comment by ayyi** [comment]
Hi

Thanks for the configure log. It looks like samplecat was built without any database support.

The easiest solution is to install libsqlite3-dev and then rerun configure and make.

I think that should fix the problem.

Regards

**Comment by ayyi** [comment]
I made a change to the configure script so that it fails if no database is enabled.

**Comment by fasteddy13** [comment]
Am on a new system now, tried to build samplecat again and got this during `make`:
```
gcc -DHAVE_CONFIG_H -I. -I../..    -DG_LOG_DOMAIN=\"Gdl\" -DGDL_UIDIR=\""/usr/local/share/gdl/ui"\" -DGTK_DISABLE_DEPRECATION_WARNINGS -DGLIB_DISABLE_DEPRECATION_WARNINGS -I/usr/local/include -I../../lib -I../../lib/waveform/lib/agl -I../../lib/waveform/gtkglext-1.0 -pthread -I/usr/include/gtk-2.0 -I/usr/lib/x86_64-linux-gnu/gtk-2.0/include -I/usr/include/pango-1.0 -I/usr/include/atk-1.0 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/harfbuzz -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/libxml2 -g -O2 -O2 -DNDEBUG -pipe -fmessage-length=200 -fdiagnostics-show-location=every-line -MT gdl-dock-master.o -MD -MP -MF .deps/gdl-dock-master.Tpo -c -o gdl-dock-master.o gdl-dock-master.c
In file included from gdl-dock-master.c:41:
registry.h:15:10: fatal error: agl/actor.h: No such file or directory
   15 | #include "agl/actor.h"
      |          ^~~~~~~~~~~~~
compilation terminated.
make[4]: *** [Makefile:584: gdl-dock-master.o] Error 1
make[4]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/gdl'
make[3]: *** [Makefile:512: all] Error 2
make[3]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib/gdl'
make[2]: *** [Makefile:421: all-recursive] Error 1
make[2]: Leaving directory '/media/steve/Apps/samplecat/samplecat/lib'
make[1]: *** [Makefile:555: all-recursive] Error 1
make[1]: Leaving directory '/media/steve/Apps/samplecat/samplecat'
make: *** [Makefile:444: all] Error 2

```

**Comment by ayyi** [comment]
Hi

This is probably caused by a missing submodule which should have been initialised by the autogen.sh script.

Can you tell me exactly what steps you took to cause this error?

The Ubuntu build test does the following:
```
git clone --branch master https://github.com/ayyi/samplecat.git
cd samplecat
git submodule update --init
./autogen.sh
./configure
make
```

If you want to try a quick fix, you could try
```
git submodule update --init --recursive
./autogen.sh
./configure
make
```

Thanks

**Comment by ayyi** [comment]
I'm assuming the issue is resolved. Please feel free to re-open.
Best regards
